name: Deploy Elicom Main Frontend

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'elicom-frontend/**'
      - '.github/workflows/deploy-elicom-main.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ELICOM_MAIN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "elicom-frontend"
          api_location: ""
          output_location: "dist/elicom-frontend"
