name: Deploy Easy-Finora Frontend

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'easy-finora-frontend/**'
      - '.github/workflows/deploy-easy-finora.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: easy-finora-frontend
        run: npm install

      - name: Build
        working-directory: easy-finora-frontend
        run: npm run build

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_EASYFINORA }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "easy-finora-frontend"
          api_location: ""
          output_location: "dist/elicom-frontend/browser"
          skip_app_build: true
